name: PHP Mess Detector
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
permissions:
  contents: read
jobs:
  PHPMD:
    name: Run PHPMD scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: 8.3
          coverage: none
          tools: phpmd
      - name: Run PHPMD
        run: phpmd . sarif phpmd.xml --reportfile phpmd-results.sarif
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3.28.13
        with:
          sarif_file: phpmd-results.sarif
          wait-for-processing: true